// ============================================================
// Classic: 56 cards | Imploding Kittens: 20 cards | Good vs Evil: 53 cards
// ============================================================

// ── CLASSIC (56 cards) 
// display_order: 1–13
export const classicCards = () => [
  {
    card_code: 'EK',
    name: 'Exploding Kitten',
    type: 'bomb',
    category: 'core',
    description: 'ถ้าจั่วใบนี้และไม่มี Defuse คุณแพ้เกม ต้องแสดงทันที',
    effect_details: { action: 'eliminate_player' },
    image_url: '/cards/classic/exploding-kitten.png',
    thumbnail_url: '/cards/classic/thumb/exploding-kitten.png',
    quantity_in_deck: 4,
    is_playable: false,
    is_stackable: false,
    expansion_pack: null,
    display_order: 1,
  },
  {
    card_code: 'DF',
    name: 'Defuse',
    type: 'defuse',
    category: 'core',
    description: 'ใช้เพื่อหยุดการระเบิด แล้วใส่ Exploding Kitten กลับในสำรับตำแหน่งที่ต้องการ',
    effect_details: { action: 'defuse_bomb', insert_back: true },
    image_url: '/cards/classic/defuse.png',
    thumbnail_url: '/cards/classic/thumb/defuse.png',
    quantity_in_deck: 6,
    is_playable: true,
    is_stackable: false,
    expansion_pack: null,
    display_order: 2,
  },
  {
    card_code: 'AT',
    name: 'Attack',
    type: 'action',
    category: 'core',
    description: 'จบเทิร์นโดยไม่จั่วไพ่ ผู้เล่นถัดไปต้องเล่น 2 เทิร์น (stack ได้)',
    effect_details: { action: 'attack', extra_turns: 2, stackable: true },
    image_url: '/cards/classic/attack.png',
    thumbnail_url: '/cards/classic/thumb/attack.png',
    quantity_in_deck: 4,
    is_playable: true,
    is_stackable: true,
    expansion_pack: null,
    display_order: 3,
  },
  {
    card_code: 'SK',
    name: 'Skip',
    type: 'action',
    category: 'core',
    description: 'จบเทิร์นโดยไม่จั่วไพ่ ถ้าใช้ตอบ Attack จะหักได้แค่ 1 เทิร์น',
    effect_details: { action: 'skip_turn' },
    image_url: '/cards/classic/skip.png',
    thumbnail_url: '/cards/classic/thumb/skip.png',
    quantity_in_deck: 4,
    is_playable: true,
    is_stackable: false,
    expansion_pack: null,
    display_order: 4,
  },
  {
    card_code: 'SF',
    name: 'See the Future',
    type: 'action',
    category: 'core',
    description: 'ดูไพ่ 3 ใบบนสุดของสำรับแบบลับ ไม่เปลี่ยนลำดับ',
    effect_details: { action: 'see_future', cards_to_see: 3, reveal_to_all: false },
    image_url: '/cards/classic/see-the-future.png',
    thumbnail_url: '/cards/classic/thumb/see-the-future.png',
    quantity_in_deck: 5,
    is_playable: true,
    is_stackable: false,
    expansion_pack: null,
    display_order: 5,
  },
  {
    card_code: 'SH',
    name: 'Shuffle',
    type: 'action',
    category: 'core',
    description: 'สับสำรับใหม่แบบสุ่ม',
    effect_details: { action: 'shuffle_deck' },
    image_url: '/cards/classic/shuffle.png',
    thumbnail_url: '/cards/classic/thumb/shuffle.png',
    quantity_in_deck: 4,
    is_playable: true,
    is_stackable: false,
    expansion_pack: null,
    display_order: 6,
  },
  {
    card_code: 'NP',
    name: 'Nope',
    type: 'reaction',
    category: 'core',
    description: 'หยุด action ใดก็ได้ ยกเว้น Exploding Kitten และ Defuse เล่นได้ทุกเวลา',
    effect_details: { action: 'nope', can_nope_nope: true, exceptions: ['bomb', 'defuse'] },
    image_url: '/cards/classic/nope.png',
    thumbnail_url: '/cards/classic/thumb/nope.png',
    quantity_in_deck: 5,
    is_playable: true,
    is_stackable: false,
    expansion_pack: null,
    display_order: 7,
  },
  {
    card_code: 'FV',
    name: 'Favor',
    type: 'action',
    category: 'core',
    description: 'บังคับผู้เล่นคนอื่นให้ส่งไพ่ 1 ใบให้คุณ (ผู้ถูกเลือกเป็นคนเลือกใบที่ให้)',
    effect_details: { action: 'steal_card', target: 'chosen_player', chooser: 'target' },
    image_url: '/cards/classic/favor.png',
    thumbnail_url: '/cards/classic/thumb/favor.png',
    quantity_in_deck: 4,
    is_playable: true,
    is_stackable: false,
    expansion_pack: null,
    display_order: 8,
  },
  // Cat Cards — 5 ชนิด × 4 ใบ = 20 ใบ
  {
    card_code: 'CAT_TACO',
    name: 'Taco Cat',
    type: 'combo',
    category: 'cat',
    description: 'ไพ่แมว ใช้คู่ 2 ใบเพื่อขโมยไพ่สุ่มจากผู้เล่นคนอื่น',
    effect_details: { action: 'combo_steal', combo_size: 2 },
    image_url: '/cards/classic/taco-cat.png',
    thumbnail_url: '/cards/classic/thumb/taco-cat.png',
    quantity_in_deck: 4,
    is_playable: true,
    is_stackable: false,
    expansion_pack: null,
    display_order: 9,
  },
  {
    card_code: 'CAT_MELON',
    name: 'Melon Cat',
    type: 'combo',
    category: 'cat',
    description: 'ไพ่แมว ใช้คู่ 2 ใบเพื่อขโมยไพ่สุ่มจากผู้เล่นคนอื่น',
    effect_details: { action: 'combo_steal', combo_size: 2 },
    image_url: '/cards/classic/melon-cat.png',
    thumbnail_url: '/cards/classic/thumb/melon-cat.png',
    quantity_in_deck: 4,
    is_playable: true,
    is_stackable: false,
    expansion_pack: null,
    display_order: 10,
  },
  {
    card_code: 'CAT_BEARD',
    name: 'Beard Cat',
    type: 'combo',
    category: 'cat',
    description: 'ไพ่แมว ใช้คู่ 2 ใบเพื่อขโมยไพ่สุ่มจากผู้เล่นคนอื่น',
    effect_details: { action: 'combo_steal', combo_size: 2 },
    image_url: '/cards/classic/beard-cat.png',
    thumbnail_url: '/cards/classic/thumb/beard-cat.png',
    quantity_in_deck: 4,
    is_playable: true,
    is_stackable: false,
    expansion_pack: null,
    display_order: 11,
  },
  {
    card_code: 'CAT_RAINBOW',
    name: 'Rainbow-Ralphing Cat',
    type: 'combo',
    category: 'cat',
    description: 'ไพ่แมว ใช้คู่ 2 ใบเพื่อขโมยไพ่สุ่มจากผู้เล่นคนอื่น',
    effect_details: { action: 'combo_steal', combo_size: 2 },
    image_url: '/cards/classic/rainbow-cat.png',
    thumbnail_url: '/cards/classic/thumb/rainbow-cat.png',
    quantity_in_deck: 4,
    is_playable: true,
    is_stackable: false,
    expansion_pack: null,
    display_order: 12,
  },
  {
    card_code: 'CAT_POTATO',
    name: 'Potato Cat',
    type: 'combo',
    category: 'cat',
    description: 'ไพ่แมว ใช้คู่ 2 ใบเพื่อขโมยไพ่สุ่มจากผู้เล่นคนอื่น',
    effect_details: { action: 'combo_steal', combo_size: 2 },
    image_url: '/cards/classic/potato-cat.png',
    thumbnail_url: '/cards/classic/thumb/potato-cat.png',
    quantity_in_deck: 4,
    is_playable: true,
    is_stackable: false,
    expansion_pack: null,
    display_order: 13,
  },
  // รวม Classic: 4+6+4+4+5+4+5+4+4+4+4+4+4 = 56 ใบ ✓
]

// ── IMPLODING KITTENS (20 cards) ─────────────────────────────
// display_order: 14–19
export const implodingKittensCards = () => [
  {
    card_code: 'IK',
    name: 'Imploding Kitten',
    type: 'bomb',
    category: 'core',
    description: 'จั่วใบนี้ face up — ตายทันที ไม่มี Defuse ช่วยได้ และ Nope ก็ไม่ได้ผล วางใส่ discard pile',
    effect_details: {
      action: 'eliminate_player',
      no_defuse: true,
      no_nope: true,
      face_up_in_deck: true,
    },
    image_url: '/cards/imploding/imploding-kitten.png',
    thumbnail_url: '/cards/imploding/thumb/imploding-kitten.png',
    quantity_in_deck: 1,
    is_playable: false,
    is_stackable: false,
    expansion_pack: 'imploding_kittens',
    display_order: 14,
  },
  {
    card_code: 'RV',
    name: 'Reverse',
    type: 'action',
    category: 'core',
    description: 'กลับทิศทางการเล่น และจบเทิร์นโดยไม่จั่วไพ่ ถ้ามี 2 คนทำหน้าที่เหมือน Skip',
    effect_details: { action: 'reverse_order', ends_turn: true },
    image_url: '/cards/imploding/reverse.png',
    thumbnail_url: '/cards/imploding/thumb/reverse.png',
    quantity_in_deck: 4,
    is_playable: true,
    is_stackable: false,
    expansion_pack: 'imploding_kittens',
    display_order: 15,
  },
  {
    card_code: 'DB',
    name: 'Draw from Bottom',
    type: 'action',
    category: 'core',
    description: 'จบเทิร์นโดยจั่วไพ่จากล่างสุดของสำรับแทนบนสุด',
    effect_details: { action: 'draw_from_bottom' },
    image_url: '/cards/imploding/draw-from-bottom.png',
    thumbnail_url: '/cards/imploding/thumb/draw-from-bottom.png',
    quantity_in_deck: 4,
    is_playable: true,
    is_stackable: false,
    expansion_pack: 'imploding_kittens',
    display_order: 16,
  },
  {
    card_code: 'TA',
    name: 'Targeted Attack',
    type: 'action',
    category: 'core',
    description: 'จบเทิร์นโดยไม่จั่วไพ่ และเลือกผู้เล่นที่ต้องเล่น 2 เทิร์น (stack ได้)',
    effect_details: {
      action: 'targeted_attack',
      extra_turns: 2,
      target: 'chosen_player',
      stackable: true,
    },
    image_url: '/cards/imploding/targeted-attack.png',
    thumbnail_url: '/cards/imploding/thumb/targeted-attack.png',
    quantity_in_deck: 3,
    is_playable: true,
    is_stackable: true,
    expansion_pack: 'imploding_kittens',
    display_order: 17,
  },
  {
    card_code: 'FC',
    name: 'Feral Cat',
    type: 'combo',
    category: 'cat',
    description: 'ใช้แทน cat card ใดก็ได้ในการทำ combo ใช้เป็นการ์ด action อื่นไม่ได้',
    effect_details: { action: 'combo_steal', combo_size: 2, wildcard: true, cat_only: true },
    image_url: '/cards/imploding/feral-cat.png',
    thumbnail_url: '/cards/imploding/thumb/feral-cat.png',
    quantity_in_deck: 4,
    is_playable: true,
    is_stackable: false,
    expansion_pack: 'imploding_kittens',
    display_order: 18,
  },
  {
    card_code: 'AF',
    name: 'Alter the Future',
    type: 'action',
    category: 'core',
    description: 'ดูไพ่ 3 ใบบนสุดแบบลับ แล้วจัดเรียงลำดับใหม่ได้ตามต้องการ',
    effect_details: { action: 'alter_future', cards_to_see: 3, reorder: true, reveal_to_all: false },
    image_url: '/cards/imploding/alter-the-future.png',
    thumbnail_url: '/cards/imploding/thumb/alter-the-future.png',
    quantity_in_deck: 4,
    is_playable: true,
    is_stackable: false,
    expansion_pack: 'imploding_kittens',
    display_order: 19,
  },
  // รวม Imploding Kittens: 1+4+4+3+4+4 = 20 ใบ ✓
  // หมายเหตุ: Cone of Shame เป็น physical item ไม่ใช่ไพ่ ไม่ต้อง seed
]

// ── GOOD VS EVIL (53 cards + Godcat + Devilcat) ───────────────
// Standalone — ไม่ต้องใช้ Classic
// display_order: 20–36
export const goodAndEvilCards = () => [
  {
    card_code: 'GVE_EK',
    name: 'Exploding Kitten',
    type: 'bomb',
    category: 'core',
    description: 'ถ้าจั่วใบนี้และไม่มี Defuse คุณแพ้เกม ต้องแสดงทันที',
    effect_details: { action: 'eliminate_player' },
    image_url: '/cards/gve/exploding-kitten.png',
    thumbnail_url: '/cards/gve/thumb/exploding-kitten.png',
    quantity_in_deck: 4,
    is_playable: false,
    is_stackable: false,
    expansion_pack: 'good_and_evil',
    display_order: 20,
  },
  {
    card_code: 'GVE_DF',
    name: 'Defuse',
    type: 'defuse',
    category: 'core',
    description: 'ใช้เพื่อหยุดการระเบิด แล้วใส่ Exploding Kitten กลับในสำรับตำแหน่งที่ต้องการ',
    effect_details: { action: 'defuse_bomb', insert_back: true },
    image_url: '/cards/gve/defuse.png',
    thumbnail_url: '/cards/gve/thumb/defuse.png',
    quantity_in_deck: 6,
    is_playable: true,
    is_stackable: false,
    expansion_pack: 'good_and_evil',
    display_order: 21,
  },
  {
    card_code: 'GVE_NP',
    name: 'Nope',
    type: 'reaction',
    category: 'core',
    description: 'หยุด action ใดก็ได้ ยกเว้น Exploding Kitten, Devilcat และ Defuse เล่นได้ทุกเวลา',
    effect_details: {
      action: 'nope',
      can_nope_nope: true,
      exceptions: ['bomb', 'devilcat', 'defuse'],
    },
    image_url: '/cards/gve/nope.png',
    thumbnail_url: '/cards/gve/thumb/nope.png',
    quantity_in_deck: 5,
    is_playable: true,
    is_stackable: false,
    expansion_pack: 'good_and_evil',
    display_order: 22,
  },
  {
    card_code: 'GVE_AT',
    name: 'Attack',
    type: 'action',
    category: 'core',
    description: 'จบเทิร์นโดยไม่จั่วไพ่ ผู้เล่นถัดไปต้องเล่น 2 เทิร์น (stack ได้)',
    effect_details: { action: 'attack', extra_turns: 2, stackable: true },
    image_url: '/cards/gve/attack.png',
    thumbnail_url: '/cards/gve/thumb/attack.png',
    quantity_in_deck: 2,
    is_playable: true,
    is_stackable: true,
    expansion_pack: 'good_and_evil',
    display_order: 23,
  },
  {
    card_code: 'GVE_TA',
    name: 'Targeted Attack',
    type: 'action',
    category: 'core',
    description: 'จบเทิร์นโดยไม่จั่วไพ่ และเลือกผู้เล่นที่ต้องเล่น 2 เทิร์น (stack ได้)',
    effect_details: {
      action: 'targeted_attack',
      extra_turns: 2,
      target: 'chosen_player',
      stackable: true,
    },
    image_url: '/cards/gve/targeted-attack.png',
    thumbnail_url: '/cards/gve/thumb/targeted-attack.png',
    quantity_in_deck: 2,
    is_playable: true,
    is_stackable: true,
    expansion_pack: 'good_and_evil',
    display_order: 24,
  },
  {
    card_code: 'GVE_SH',
    name: 'Shuffle',
    type: 'action',
    category: 'core',
    description: 'สับสำรับใหม่แบบสุ่ม',
    effect_details: { action: 'shuffle_deck' },
    image_url: '/cards/gve/shuffle.png',
    thumbnail_url: '/cards/gve/thumb/shuffle.png',
    quantity_in_deck: 2,
    is_playable: true,
    is_stackable: false,
    expansion_pack: 'good_and_evil',
    display_order: 25,
  },
  {
    card_code: 'GVE_RF',
    name: 'Reveal the Future',
    type: 'action',
    category: 'core',
    description: 'เปิดไพ่ 3 ใบบนสุดให้ผู้เล่นทุกคนเห็น แล้วคืนกลับโดยไม่เปลี่ยนลำดับ',
    effect_details: { action: 'reveal_future', cards_to_see: 3, reveal_to_all: true },
    image_url: '/cards/gve/reveal-the-future.png',
    thumbnail_url: '/cards/gve/thumb/reveal-the-future.png',
    quantity_in_deck: 3,
    is_playable: true,
    is_stackable: false,
    expansion_pack: 'good_and_evil',
    display_order: 26,
  },
  {
    card_code: 'GVE_FV',
    name: 'Favor',
    type: 'action',
    category: 'core',
    description: 'บังคับผู้เล่นคนอื่นให้ส่งไพ่ 1 ใบให้คุณ (ผู้ถูกเลือกเป็นคนเลือกใบที่ให้)',
    effect_details: { action: 'steal_card', target: 'chosen_player', chooser: 'target' },
    image_url: '/cards/gve/favor.png',
    thumbnail_url: '/cards/gve/thumb/favor.png',
    quantity_in_deck: 4,
    is_playable: true,
    is_stackable: false,
    expansion_pack: 'good_and_evil',
    display_order: 27,
  },
  {
    card_code: 'GVE_RH',
    name: 'Raising Heck',
    type: 'action',
    category: 'core',
    description: 'จั่วไพ่จากล่างสุด แล้วเลือกเก็บไว้หรือวางคืนบนสุดของสำรับ จบเทิร์น',
    effect_details: { action: 'draw_from_bottom', keep_or_return: true },
    image_url: '/cards/gve/raising-heck.png',
    thumbnail_url: '/cards/gve/thumb/raising-heck.png',
    quantity_in_deck: 2,
    is_playable: true,
    is_stackable: false,
    expansion_pack: 'good_and_evil',
    display_order: 28,
  },
  {
    card_code: 'GVE_AG',
    name: 'Armageddon',
    type: 'action',
    category: 'special',
    description: 'เริ่ม Armageddon — แจก Godcat/Devilcat ให้ผู้เล่น ใช้ได้เมื่อ Godcat อยู่บน Playmat เท่านั้น จบเทิร์นโดยไม่จั่วไพ่',
    effect_details: {
      action: 'armageddon',
      requires_godcat_on_playmat: true,
      ends_turn: true,
      no_draw: true,
      can_be_noped: true,
    },
    image_url: '/cards/gve/armageddon.png',
    thumbnail_url: '/cards/gve/thumb/armageddon.png',
    quantity_in_deck: 3,
    is_playable: true,
    is_stackable: false,
    expansion_pack: 'good_and_evil',
    display_order: 29,
  },
  // Special Cards — card back ต่างจากไพ่อื่น
  {
    card_code: 'GVE_GC',
    name: 'Godcat',
    type: 'special',
    category: 'special',
    description: 'การ์ดทรงพลังที่สุด ใช้แทนการ์ดใดก็ได้ ยกเว้น Nope หลังเล่นให้วางคืน Playmat (ไม่ทิ้งใน Discard Pile)',
    effect_details: {
      action: 'wildcard',
      can_be_any_card: true,
      except: ['nope'],
      after_use: 'return_to_playmat',
      unique_card_back: true,
    },
    image_url: '/cards/gve/godcat.png',
    thumbnail_url: '/cards/gve/thumb/godcat.png',
    quantity_in_deck: 1,
    is_playable: true,
    is_stackable: false,
    expansion_pack: 'good_and_evil',
    display_order: 30,
  },
  {
    card_code: 'GVE_DC',
    name: 'Devilcat',
    type: 'special',
    category: 'special',
    description: 'ผู้ที่ได้ Devilcat ใน Armageddon ต้องใช้ Defuse หรือตาย ห้ามใส่กลับสำรับ วางคืน Playmat เสมอ',
    effect_details: {
      action: 'eliminate_or_defuse',
      never_in_draw_pile: true,
      after_use: 'return_to_playmat',
      unique_card_back: true,
    },
    image_url: '/cards/gve/devilcat.png',
    thumbnail_url: '/cards/gve/thumb/devilcat.png',
    quantity_in_deck: 1,
    is_playable: false,
    is_stackable: false,
    expansion_pack: 'good_and_evil',
    display_order: 31,
  },
  // Cat Cards — 4 ชนิด × 4 ใบ = 16 ใบ แต่เราใช้แค่ 2 พอ
  {
    card_code: 'GVE_FC',
    name: 'Feral Cat',
    type: 'combo',
    category: 'cat',
    description: 'ใช้แทน cat card ใดก็ได้ในการทำ combo ใช้เป็นการ์ด action อื่นไม่ได้',
    effect_details: { action: 'combo_steal', combo_size: 2, wildcard: true, cat_only: true },
    image_url: '/cards/gve/feral-cat.png',
    thumbnail_url: '/cards/gve/thumb/feral-cat.png',
    quantity_in_deck: 9,
    is_playable: true,
    is_stackable: false,
    expansion_pack: 'good_and_evil',
    display_order: 32,
  },
  {
    card_code: 'GVE_MC',
    name: 'Mercat',
    type: 'combo',
    category: 'cat',
    description: 'ไพ่แมว ใช้คู่ 2 ใบเพื่อขโมยไพ่สุ่มจากผู้เล่นคนอื่น',
    effect_details: { action: 'combo_steal', combo_size: 2 },
    image_url: '/cards/gve/mercat.png',
    thumbnail_url: '/cards/gve/thumb/mercat.png',
    quantity_in_deck: 9,
    is_playable: true,
    is_stackable: false,
    expansion_pack: 'good_and_evil',
    display_order: 33,
  },
  // รวม good vs evil: 4+6+5+2+2+2+3+4+2+3+1+1+9+9= 53 ใบ ✓
]