export enum CardCode {
  EXPLODING_KITTEN = "EK",
  GVE_EXPLODING_KITTEN = "GVE_EK",
  DEFUSE = "DF",
  GVE_DEFUSE = "GVE_DF",
  IMPLODING_KITTEN = "IK",
  ATTACK = "AT",
  SKIP = "SK",
  SEE_THE_FUTURE = "SF",
  SHUFFLE = "SH",
  NOPE = "NP",
  FAVOR = "FV",
  TARGETED_ATTACK = "TA",
  REVERSE = "RV",
  DRAW_FROM_BOTTOM = "DB",
  ALTER_THE_FUTURE = "AF",
  MIAO_MACO = "MC",
  FERAL_CAT = "FC"
}

export enum ActionType {
  GAME_STARTED = "GAME_STARTED",
  DREW_CARD = "DREW_CARD",
  DREW_EXPLODING_KITTEN = "DREW_EXPLODING_KITTEN",
  PLAY_CARD = "PLAY_CARD",
  DEFUSED = "DEFUSED",
  EK_INSERTED = "EK_INSERTED",
  PLAYER_ELIMINATED = "PLAYER_ELIMINATED",
  PLAYER_AFK_KICKED = "PLAYER_AFK_KICKED",
  GAME_FINISHED = "GAME_FINISHED",
  TURN_ADVANCED = "TURN_ADVANCED",
  GAME_OVER = "GAME_OVER",
  WAITING_FOR_INSERT = "WAITING_FOR_INSERT",
  CARD_PLAYED = "CARD_PLAYED",
  // Favor-related actions
  FAVOR_PENDING="FAVOR_PENDING",
  FAVOR_RESPONSE= "FAVOR_RESPONSE",
  // Nope-related actions
  NOPE_PLAYED = "NOPE_PLAYED",

}

export const GAME_CONFIG = {
  AFK_KICK_THRESHOLD: 2,
  TURN_TIMER_SECONDS: 30,
  ROOM_CODE_LENGTH: 6,
  MAX_ROOM_CODE_RETRIES: 10,
};
